//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HauLe.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewMenuSanPham
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tag { get; set; }
        public string Image { get; set; }
        public Nullable<int> IDthuonghieu { get; set; }
        public string Mausac { get; set; }
        public string Kichthuoc { get; set; }
        public Nullable<double> Giaban { get; set; }
        public Nullable<double> Phantramkhuyenmai { get; set; }
        public string Donvi { get; set; }
        public Nullable<int> Luotxem { get; set; }
        public string Luotdanhgia { get; set; }
        public Nullable<bool> Vat { get; set; }
        public string Khuyenmai { get; set; }
        public string Baohanh { get; set; }
        public string seri { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string Content { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Keyword { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<int> Active { get; set; }
        public string Lang { get; set; }
        public string GroupNewsCatTag { get; set; }
        public string MenuSanPhamGoc { get; set; }
        public string MenuSanPhamCha { get; set; }
        public string MenuSanPhamCha_con { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string Images5 { get; set; }
        public string thongdiep { get; set; }
        public Nullable<int> order { get; set; }
        public string NameEn { get; set; }
        public string ContentEn { get; set; }
        public string DetailEn { get; set; }
        public Nullable<int> Soluongmua { get; set; }
        public string khuyenmaiEn { get; set; }
        public string BaohanhEn { get; set; }
        public string DacDiemNoiBat { get; set; }
        public string DacDiemNoiBatEn { get; set; }
        public string ThongdiepEn { get; set; }
    }
}
