//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HauLe.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBill_customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbBill_customers()
        {
            this.tbBilldetails = new HashSet<tbBilldetail>();
        }
    
        public int billid { get; set; }
        public Nullable<int> userid { get; set; }
        public string totalmoney { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<System.DateTime> xdate { get; set; }
        public string request { get; set; }
        public string typepay { get; set; }
        public Nullable<int> state { get; set; }
        public string lang { get; set; }
        public Nullable<int> show { get; set; }
    
        public virtual tbCUSTOMER tbCUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBilldetail> tbBilldetails { get; set; }
    }
}
