//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HauLe.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMausac
    {
        public int IDmau { get; set; }
        public string Tenmau { get; set; }
        public string Hinhanh { get; set; }
        public string Lang { get; set; }
        public string TenmauEn { get; set; }
    }
}
